[package]
name = "rust00"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "number"
path = "src/number/main.rs"

[[bin]]
name = "web"
path = "src/web/main.rs"

[[bin]]
name = "mandelbrot"
path = "src/mandelbrot/main.rs"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
num = "0.4"
image = "0.13"
crossbeam = "0.8"